#!/usr/bin/env python3
"""Wrap .gnos diagrams in LaTeX documents, one page per diagram.

Each page is A4 with the diagram centered and its caption -- carried by the
.gnos file itself -- underneath. Paths to the .gnos files are written relative
to the .tex file, so a generated document also compiles by hand with
`pdflatex name.tex` from its own directory (with TEXINPUTS pointing at
sgf2pdf.sty).

Usage:
    gnos2tex.py                            # gnos/ -> pages/, one .tex each
    gnos2tex.py --indir IN --outdir OUT    # directory mode
    gnos2tex.py FILE.gnos -o FILE.tex      # single file (used by the Makefile)
    gnos2tex.py --all all.tex FILE...      # one document holding every page
"""

import argparse
import glob
import os
import sys

PREAMBLE = r"""%% Generated by gnos2tex.py -- do not edit; edit the .sgf instead.
\documentclass[a4paper,11pt]{article}
\usepackage[a4paper,margin=2.2cm]{geometry}
\usepackage{mlmodern}
\usepackage[T1]{fontenc}
\usepackage[size=%(size)s]{sgf2pdf}
\pagestyle{empty}
\begin{document}
"""

PAGE = r"""\null\vfill
\begin{center}
\gobandiagram{%(gnos)s}
\end{center}
\vfill\null
"""

POSTAMBLE = r"""\end{document}
"""


def render(gnos_paths_from_tex, size):
    """A document with one page per path. Paths must be relative to the .tex."""
    pages = [PAGE % {"gnos": p} for p in gnos_paths_from_tex]
    return PREAMBLE % {"size": size} + "\\clearpage\n".join(pages) + POSTAMBLE


def write_tex(srcs, dst, size):
    parent = os.path.dirname(dst) or "."
    os.makedirs(parent, exist_ok=True)
    # LaTeX wants forward slashes, and the paths must be relative to the .tex.
    rel = [os.path.relpath(src, parent).replace(os.sep, "/") for src in srcs]
    with open(dst, "w", encoding="utf-8") as f:
        f.write(render(rel, size))


def resolve_inputs(inputs, indir):
    """The .gnos files to act on: explicit files, a directory, or --indir."""
    if len(inputs) == 1 and os.path.isdir(inputs[0]):
        indir = inputs[0]
    elif inputs:
        return list(inputs)
    return sorted(glob.glob(os.path.join(indir, "*.gnos")))


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("inputs", nargs="*", help=".gnos files, or a directory of them")
    parser.add_argument("-o", "--output", help="output .tex file (single-file mode)")
    parser.add_argument("--all", metavar="FILE.tex",
                        help="write one document containing every page, in order")
    parser.add_argument("--indir", default="gnos", help="input directory (default: gnos)")
    parser.add_argument("--outdir", default="pages", help="output directory (default: pages)")
    parser.add_argument("--size", default="16", help="board font size in points (default: 16)")
    args = parser.parse_args()

    if args.all and args.output:
        parser.error("--all and -o/--output are mutually exclusive")

    paths = resolve_inputs(args.inputs, args.indir)
    if not paths:
        where = args.inputs[0] if args.inputs else args.indir
        print(f"No .gnos files found in {where}/", file=sys.stderr)
        return 1

    if args.all:
        write_tex(paths, args.all, args.size)
        return 0

    if args.output:
        if len(paths) != 1:
            parser.error("-o/--output only applies to a single .gnos file")
        write_tex(paths, args.output, args.size)
        return 0

    os.makedirs(args.outdir, exist_ok=True)
    for path in paths:
        stem = os.path.splitext(os.path.basename(path))[0]
        write_tex([path], os.path.join(args.outdir, stem + ".tex"), args.size)
    print(f"Wrote {len(paths)} .tex files to {args.outdir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
